### ISSUE TITLE
Dependencies on sortinghat and MySQLdb not declared

### ISSUE THREAD

**Issue by sebix** [grimoirelab/GrimoireELK#101]
Noticed this when running the tests in a build environment. They should be in install_requires or extras_requires

**Comment by jgbarah** [comment]
Thanks! Both are dependencies that are only needed for tests. grimoire-elk may work with them or or not. You're completely right, we will add them (maybe in test_requires).

**Comment by jgbarah** [comment]
@sebix, if you have some spare mintues, please check if #115 addresses your concerns in this issue.
