### ISSUE TITLE
Perceval in GrimoireELK

### ISSUE THREAD

**Issue by assadOW2** [grimoirelab/GrimoireELK#107]
I followed instuctions here to install virtual environment for GrimoireELK: https://grimoirelab.gitbooks.io/training/content/grimoireelk/installation.html

When running perceval, I have this message:

```
Traceback (most recent call last):
  File "/home/assadm/venvs/grimoireelk/bin/perceval", line 82, in <module>
    """%(prog)s """  + perceval.__version__
AttributeError: module 'perceval' has no attribute '__version__'
```

I followed previous tutorial, https://grimoirelab.gitbooks.io/training/content/perceval/first_steps.html, and perceval works fine.

**Comment by jgbarah** [comment]
We had a problem with namespaces when packaging that version. Could you please check with the latest pip packages, and report back if the problem persists, or it works?

**Comment by assadOW2** [comment]
It's working now, I just tried it with elasticgirl 19.1 release.

**Comment by jgbarah** [comment]
Thx!!
