### ISSUE TITLE
mbox backend and p2o.py 

### ISSUE THREAD

**Issue by assadOW2** [grimoirelab/GrimoireELK#108]
I followed Peceval tutorials and created mbox files in a directory named "archives" (https://grimoirelab.gitbooks.io/training/content/perceval/mail.html)

I would like to use p2o.py to create an index from mbox backend
Unfortunately, I have this error:

```
(grimoireelk) assadm@assadm-ThinkPad-T470p:~$ p2o.py --enrich --index mbox_raw --index-enrich mbox e http://localhost:9200 --no_inc --debug mbox httpd-announce archives
Traceback (most recent call last):
  File "/home/assadm/venvs/grimoireelk/bin/p2o.py", line 132, in <module>
    args.index, args.index_enrich, args.project)
  File "/home/assadm/venvs/grimoireelk/lib/python3.5/site-packages/grimoire_elk/arthur.py", line 56, in feed_backend
    raise RuntimeError("Unknown backend %s" % backend_name)
RuntimeError: Unknown backend e

```
For the record, I have no issues with git backend, as in the tutorial.

**Comment by acs** [comment]
Checking your command, I have found an error:

`p2o.py --enrich --index mbox_raw --index-enrich mbox e http://localhost:9200 --no_inc --debug mbox httpd-announce archives
`
this must be:

`p2o.py --enrich --index mbox_raw --index-enrich mbox -e http://localhost:9200 --no_inc --debug mbox httpd-announce archives
`
The typo is in "-e". Could you confirm that the errata is also in the tutorial?

**Comment by assadOW2** [comment]
A bad copy/paste from me, the tutorial typo is correct for git:

```
(grimoireelk) $ p2o.py --enrich --index git_raw --index-enrich git \
  -e http://localhost:9200 --no_inc --debug \
  git https://github.com/grimoirelab/perceval.git
```
Thanks for the quick answer, it's working with correct typo.
