### ISSUE TITLE
JSON serializing crash

### ISSUE THREAD

**Issue by BenLloydPearson** [grimoirelab/GrimoireELK#36]
Hello,

I'm using the fosdem16 branch of Perceval as outlined in the first use case. While trying to use GrimoireELK to bring data from the Linux Kernel git log into elasticsearch I ran into a single commit that was causing Perceval to crash. 

Here is the beginning of the error log:
`Error feeding ocean from git (linux.gitlog): 'utf-8' codec can't decode byte 0xf6 in position 5329: invalid start byte
Traceback (most recent call last):
  File "GrimoireELK/utils/grimoire/arthur.py", line 76, in feed_backend
    ocean_backend.feed()
  File "GrimoireELK/utils/grimoire/ocean/elastic.py", line 111, in feed
    for item in items:
  File "gitlab/lib/python3.4/site-packages/perceval/backend.py", line 161, in decorator
    for item in func(self, *args, **kwargs):
  File "gitlab/lib/python3.4/site-packages/perceval/backends/git.py", line 73, in fetch
    commits = [commit for commit in self.parse_git_log(self.gitlog)]
  File "gitlab/lib/python3.4/site-packages/perceval/backends/git.py", line 73, in <listcomp>
    commits = [commit for commit in self.parse_git_log(self.gitlog)]
  File "gitlab/lib/python3.4/site-packages/perceval/backends/git.py", line 102, in parse_git_log
    for commit in parser.parse():
  File "gitlab/lib/python3.4/site-packages/perceval/backends/git.py", line 277, in parse
    for line in self.stream:
  File "gitlab/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 5329: invalid start byte` 

I identified the culprit [to be this commit](http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=1a876762064b8e1ff9a65e78a7cba09eb765a54b). 

The line that causes it is this: "From "Uwe Kleine-K�nig" u.kleine-koenig@pengutronix.de:"

Deleting the � (which should be an o umlaut) resolves the problem.

**Comment by jgbarah** [comment]
Info from @BenLloydPearson via IRC:

> this is what the character is ouput as in the JSON stream: \xf6
> i.e: "From  "Uwe Kleine-K\xf6nig""

The process for getting this error is using the  vanilla instructions in the FOSDEM use case on the Torvalds Linux repo.

**Comment by acs** [comment]
@BenLloydPearson are you interested in this issue or we can close it? The software has evolved a lot and probably if you are interested it is better to reproduce it with current versions and then work in this scenario. What do you think?

**Comment by BenLloydPearson** [comment]
I think it can probably be closed. I've been testing the latest version of everything over the past couple of weeks and it seems Perceval properly handles these problems now. Granted, I haven't tested with the specific commit I was running into the problem with, but if it does continue to cause problems I can reopen this bug or submit a new one.

Thanks for your work!

**Comment by jgbarah** [comment]
Great! Closing it then. Please reopen or submit a new issue if you find a problem again.
