### ISSUE TITLE
Question: how to use Slack backend and p2o

### ISSUE THREAD

**Issue by robinmuilwijk** [grimoirelab/GrimoireELK#84]
I got Slack working, or at least partially. I run the following command:

p2o.py --enrich --index slack_raw --index-enrich slack -e http://localhost:9200 --debug slack C06BF20AH --from-date 2015-06-01 -t mySlackToken

What this does, is that it loads 100 messages from the Slack channel, but from today and backwards. It does not start at the given date 2015-06-01 so I can't seem to load the full history of that channel.

Am I doing something wrong?

And additionally, if I want to load more channels of that Slack team into the index, do I run separate commands and do I need to use --project at all?

**Comment by robinmuilwijk** [comment]
I tried using --tag and define a channelname. And then load two channels that way into the single index. But the second command does not load any data.

I have also tried using a more recent date for the --from-date, this now results in loading 200 messages, but I would expect this to be higher.

**Comment by acs** [comment]
@robinmuilwijk it seems slack API returns messages just from the past n-days. From our testing n seems to be 13 days. But I can not find any documentation related to it. 

I have tested to load two channels in the same index with p2o and I have no issues. And also, the --from-date param is working for me has expected.

**Comment by robinmuilwijk** [comment]
@acs thanks for the feedback, I am going to try this again, I'll let you know the results.

**Comment by robinmuilwijk** [comment]
It works! What I changed in my command was to remove --debug. I set the --from-date to 2017-01-01 and it is pulling in messages from April 10 to today. By only changing the channel ID, I can now load several channels into my slack index.

**Comment by acs** [comment]
@robin that's great. Could you confirm that the messages collected are not the full history?

**Comment by robinmuilwijk** [comment]
@acs you are correct, I confirm that not the full history is being fetched. It fetches messages from today and then back in time, for an x-amount of messages. Whenever I schedule my commands, it will continue to load messages incremental.
